version: '3.9'

services:

    database:
        container_name: database_user
        image: postgres:alpine
        ports:
            - "$POSTGRES_PORT:5432"
        environment:
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD